#!/usr/bin/env -S pnpm exec tsx
/**
 * Regenerates `packages/core/src/rules/confusables.generated.ts` from Unicode's UTS #39
 * `confusables.txt`, pinned by version and SHA-256 (see `docs/DECISIONS.md`). Keeps only the
 * mappings of a single code point to a single ASCII letter or digit: that is all the token
 * impersonation check (VGL-W008) compares. The output is committed; re-run this script and review
 * the diff when moving to a new Unicode version.
 *
 * Usage: pnpm exec tsx scripts/generate-confusables.ts
 */
import { createHash } from "node:crypto";
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const VERSION = "18.0.0";
const URL_ = `https://www.unicode.org/Public/${VERSION}/security/confusables.txt`;
const SHA256 = "6ed3ee967c9dfdf6677d563c9985182fbc50a2efb7d6059cd57b2e2ce18f5b92";

const repoRoot = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const outPath = path.join(repoRoot, "packages/core/src/rules/confusables.generated.ts");

async function main(): Promise<void> {
  const response = await fetch(URL_);
  if (!response.ok) {
    throw new Error(`GET ${URL_} failed: ${response.status}`);
  }
  const bytes = new Uint8Array(await response.arrayBuffer());
  const hash = createHash("sha256").update(bytes).digest("hex");
  if (hash !== SHA256) {
    throw new Error(`confusables.txt SHA-256 is ${hash}, expected ${SHA256}`);
  }
  const text = new TextDecoder("utf-8", { fatal: true }).decode(bytes).replace(/^\uFEFF/, "");

  const entries: [number, string][] = [];
  for (const line of text.split("\n")) {
    const data = line.split("#")[0]?.trim() ?? "";
    if (data === "") {
      continue;
    }
    const [source, target] = data.split(";").map((field) => field.trim());
    if (source === undefined || target === undefined || source.includes(" ")) {
      continue;
    }
    const targetChars = target
      .split(" ")
      .map((hex) => String.fromCodePoint(Number.parseInt(hex, 16)));
    const mapped = targetChars.join("");
    if (targetChars.length === 1 && /^[A-Za-z0-9]$/.test(mapped)) {
      entries.push([Number.parseInt(source, 16), mapped]);
    }
  }
  entries.sort((a, b) => a[0] - b[0]);

  // Keys are written as `\u{...}` escapes so the file never contains the look-alike (or
  // invisible) characters themselves.
  const pairs = entries.map(
    ([cp, target]) => `["\\u{${cp.toString(16).toUpperCase()}}", "${target}"]`,
  );
  const lines: string[] = [];
  let current = "";
  for (const pair of pairs) {
    if (current.length + pair.length + 2 > 94) {
      lines.push(current);
      current = "";
    }
    current = current === "" ? pair : `${current}, ${pair}`;
  }
  lines.push(current);

  const source = `// Generated by scripts/generate-confusables.ts from Unicode ${VERSION} confusables.txt
// (${URL_},
// SHA-256 ${SHA256}). Do not edit by hand.
// Unicode data © Unicode, Inc., used under the Unicode License (https://www.unicode.org/terms_of_use.html).

export const CONFUSABLES_VERSION = "${VERSION}";

/** Every single character that UTS #39 maps to one ASCII letter or digit, and that letter or digit. */
export const CONFUSABLES: ReadonlyMap<string, string> = new Map<string, string>([
${lines.map((line) => `  ${line},`).join("\n")}
]);
`;
  await writeFile(outPath, source);
  console.log(`Wrote ${entries.length} mappings to ${outPath}`);
}

await main();
