import type { Rule } from "./types.js";

const SEVERITY_TITLES = { critical: "Critical", info: "Info", warning: "Warning" } as const;

/** `docs/rules.md`, generated from the rules' own metadata (`pnpm docs:rules`). */
export function renderRulesMarkdown(rules: readonly Rule[]): string {
  const lines = [
    "# Risk rules",
    "",
    "<!-- Generated by `pnpm docs:rules` from the rule metadata in `packages/core/src/rules/`. Do not edit by hand. -->",
    "",
    "Every finding carries its rule id, a severity, concrete evidence and where the information comes from (provenance).",
    "The verdict is `critical` if any critical finding; otherwise `incomplete` if the analysis has any gap; otherwise `attention` if any warning; otherwise `no-findings` (shown as “No findings from the checks performed”, never as “safe”).",
    "Findings about an instruction inside a Squads proposal that the analysed transaction only creates are marked as proposed: they happen only if that proposal is later approved and executed.",
    "",
  ];
  for (const severity of ["critical", "warning", "info"] as const) {
    lines.push(`## ${SEVERITY_TITLES[severity]}`, "");
    for (const rule of rules.filter((r) => r.defaultSeverity === severity)) {
      lines.push(
        `### ${rule.id} — ${rule.name}`,
        "",
        `**What it checks.** ${rule.docs.what}`,
        "",
        `**Why it matters.** ${rule.docs.why}`,
        "",
        `**False positives.** ${rule.docs.falsePositives}`,
        "",
      );
    }
  }
  return `${lines.join("\n").trimEnd()}\n`;
}
